-- SUPER_LINE_LEADER.APMS_CUSTOMER definition

CREATE TABLE "APMS_CUSTOMER" 
   (	"ID" VARCHAR2(36 CHAR), 
	"NAME" VARCHAR2(100 CHAR) NOT NULL ENABLE, 
	"CODE" VARCHAR2(50 CHAR), 
	"CREATED_BY" VARCHAR2(100 CHAR) NOT NULL ENABLE, 
	"CREATED_AT" TIMESTAMP (6) NOT NULL ENABLE, 
	"UPDATED_BY" VARCHAR2(100 CHAR), 
	"UPDATED_AT" TIMESTAMP (6), 
	 PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AEP_LEADER"  ENABLE, 
	 UNIQUE ("NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AEP_LEADER"  ENABLE, 
	 UNIQUE ("CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AEP_LEADER"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AEP_LEADER" ;

CREATE UNIQUE INDEX "SYS_C0018062" ON "APMS_CUSTOMER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AEP_LEADER" ;
  CREATE UNIQUE INDEX "SYS_C0018063" ON "APMS_CUSTOMER" ("NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AEP_LEADER" ;
  CREATE UNIQUE INDEX "SYS_C0018064" ON "APMS_CUSTOMER" ("CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AEP_LEADER" ;


-- SUPER_LINE_LEADER.APMS_EMAIL_CONFIGURATION definition

CREATE TABLE "APMS_EMAIL_CONFIGURATION" 
   (	"ID" VARCHAR2(36 CHAR), 
	"SMTP_HOST" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"SMTP_PORT" NUMBER(5,0) DEFAULT 587, 
	"EMAIL_FROM" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"EMAIL_PASSWORD" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"ENABLED" NUMBER(1,0) DEFAULT 1, 
	"CREATED_BY" VARCHAR2(100 CHAR) NOT NULL ENABLE, 
	"CREATED_AT" TIMESTAMP (6) NOT NULL ENABLE, 
	"UPDATED_BY" VARCHAR2(100 CHAR), 
	"UPDATED_AT" TIMESTAMP (6), 
	"SMTP_USERNAME" VARCHAR2(255 CHAR), 
	"SMTP_DOMAIN" VARCHAR2(255 CHAR), 
	"EMAIL_FROM_DISPLAY_NAME" VARCHAR2(255 CHAR), 
	"ENABLE_SSL" NUMBER(1,0) DEFAULT 0, 
	 PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AEP_LEADER"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AEP_LEADER" ;

CREATE UNIQUE INDEX "SYS_C0018268" ON "APMS_EMAIL_CONFIGURATION" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AEP_LEADER" ;

COMMENT ON TABLE SUPER_LINE_LEADER.APMS_EMAIL_CONFIGURATION IS '邮件服务器配置表';
COMMENT ON COLUMN SUPER_LINE_LEADER.APMS_EMAIL_CONFIGURATION.SMTP_HOST IS 'SMTP服务器地址';
COMMENT ON COLUMN SUPER_LINE_LEADER.APMS_EMAIL_CONFIGURATION.SMTP_PORT IS 'SMTP服务器端口 (25-标准SMTP, 587-STARTTLS)';
COMMENT ON COLUMN SUPER_LINE_LEADER.APMS_EMAIL_CONFIGURATION.EMAIL_FROM IS '发件人邮箱';
COMMENT ON COLUMN SUPER_LINE_LEADER.APMS_EMAIL_CONFIGURATION.EMAIL_PASSWORD IS '邮箱密码';
COMMENT ON COLUMN SUPER_LINE_LEADER.APMS_EMAIL_CONFIGURATION.ENABLED IS '是否启用';
COMMENT ON COLUMN SUPER_LINE_LEADER.APMS_EMAIL_CONFIGURATION.SMTP_USERNAME IS 'SMTP认证用户名';
COMMENT ON COLUMN SUPER_LINE_LEADER.APMS_EMAIL_CONFIGURATION.SMTP_DOMAIN IS 'SMTP认证域';
COMMENT ON COLUMN SUPER_LINE_LEADER.APMS_EMAIL_CONFIGURATION.EMAIL_FROM_DISPLAY_NAME IS '发件人显示名称';
COMMENT ON COLUMN SUPER_LINE_LEADER.APMS_EMAIL_CONFIGURATION.ENABLE_SSL IS '是否启用SSL加密';


-- SUPER_LINE_LEADER.APMS_EXEC_TASK definition

CREATE TABLE "APMS_EXEC_TASK" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 ORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"TASK_NAME" VARCHAR2(16), 
	"TASK_CODE" VARCHAR2(16), 
	"START_TIME" TIMESTAMP (6), 
	"END_TIME" TIMESTAMP (6), 
	"REMARK" VARCHAR2(64), 
	"EXEC_LOG" VARCHAR2(255), 
	 CONSTRAINT "APMS_EXEC_TASK_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AEP_LEADER"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AEP_LEADER" ;

CREATE UNIQUE INDEX "APMS_EXEC_TASK_PK" ON "APMS_EXEC_TASK" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AEP_LEADER" ;

COMMENT ON TABLE SUPER_LINE_LEADER.APMS_EXEC_TASK IS '定时任务执行日志记录';
COMMENT ON COLUMN SUPER_LINE_LEADER.APMS_EXEC_TASK.TASK_CODE IS '任务代码';
COMMENT ON COLUMN SUPER_LINE_LEADER.APMS_EXEC_TASK.START_TIME IS '任务执行开始时间';
COMMENT ON COLUMN SUPER_LINE_LEADER.APMS_EXEC_TASK.END_TIME IS '结束时间';
COMMENT ON COLUMN SUPER_LINE_LEADER.APMS_EXEC_TASK.REMARK IS '执行标记';
COMMENT ON COLUMN SUPER_LINE_LEADER.APMS_EXEC_TASK.EXEC_LOG IS '执行日志';


-- SUPER_LINE_LEADER.APMS_IMPORT_RECORD definition

CREATE TABLE "APMS_IMPORT_RECORD" 
   (	"ID" VARCHAR2(36 CHAR) NOT NULL ENABLE, 
	"IMPORT_TYPE" VARCHAR2(50 CHAR) NOT NULL ENABLE, 
	"FILE_NAME" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"STATUS" VARCHAR2(20 CHAR) NOT NULL ENABLE, 
	"TOTAL_COUNT" NUMBER(10,0) DEFAULT 0 NOT NULL ENABLE, 
	"SUCCESS_COUNT" NUMBER(10,0) DEFAULT 0 NOT NULL ENABLE, 
	"FAIL_COUNT" NUMBER(10,0) DEFAULT 0 NOT NULL ENABLE, 
	"FAIL_LOGS" CLOB, 
	"CREATED_BY" VARCHAR2(100 CHAR) NOT NULL ENABLE, 
	"CREATED_AT" TIMESTAMP (6) NOT NULL ENABLE, 
	"IMPORT_LOGS" CLOB, 
	 CONSTRAINT "PK_APMS_IMPORT_RECORD" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AEP_LEADER"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AEP_LEADER" 
 LOB ("FAIL_LOGS") STORE AS SECUREFILE (
  TABLESPACE "AEP_LEADER" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("IMPORT_LOGS") STORE AS SECUREFILE (
  TABLESPACE "AEP_LEADER" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

CREATE UNIQUE INDEX "PK_APMS_IMPORT_RECORD" ON "APMS_IMPORT_RECORD" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AEP_LEADER" ;
  CREATE UNIQUE INDEX "SYS_IL0000112759C00008$$" ON "APMS_IMPORT_RECORD" (
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AEP_LEADER" 
  PARALLEL (DEGREE 0 INSTANCES 0) ;
  CREATE UNIQUE INDEX "SYS_IL0000112759C00011$$" ON "APMS_IMPORT_RECORD" (
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AEP_LEADER" 
  PARALLEL (DEGREE 0 INSTANCES 0) ;

COMMENT ON TABLE SUPER_LINE_LEADER.APMS_IMPORT_RECORD IS 'Excel 导入历史记录';
COMMENT ON COLUMN SUPER_LINE_LEADER.APMS_IMPORT_RECORD.ID IS '主键 UUID';
COMMENT ON COLUMN SUPER_LINE_LEADER.APMS_IMPORT_RECORD.IMPORT_TYPE IS '导入类型：return_order / part';
COMMENT ON COLUMN SUPER_LINE_LEADER.APMS_IMPORT_RECORD.FILE_NAME IS '上传文件名';
COMMENT ON COLUMN SUPER_LINE_LEADER.APMS_IMPORT_RECORD.STATUS IS '状态：processing / completed / failed';
COMMENT ON COLUMN SUPER_LINE_LEADER.APMS_IMPORT_RECORD.TOTAL_COUNT IS '数据总行数';
COMMENT ON COLUMN SUPER_LINE_LEADER.APMS_IMPORT_RECORD.SUCCESS_COUNT IS '成功行数';
COMMENT ON COLUMN SUPER_LINE_LEADER.APMS_IMPORT_RECORD.FAIL_COUNT IS '失败行数';
COMMENT ON COLUMN SUPER_LINE_LEADER.APMS_IMPORT_RECORD.FAIL_LOGS IS '失败日志 JSON 数组 [{row, error}]';
COMMENT ON COLUMN SUPER_LINE_LEADER.APMS_IMPORT_RECORD.CREATED_BY IS '操作人';
COMMENT ON COLUMN SUPER_LINE_LEADER.APMS_IMPORT_RECORD.CREATED_AT IS '操作时间';


-- SUPER_LINE_LEADER.APMS_NOTIFICATION_LOG definition

CREATE TABLE "APMS_NOTIFICATION_LOG" 
   (	"ID" VARCHAR2(36 CHAR), 
	"PART_ID" VARCHAR2(36 CHAR) NOT NULL ENABLE, 
	"NOTIFICATION_TYPE" VARCHAR2(30 CHAR) NOT NULL ENABLE, 
	"RECIPIENTS" VARCHAR2(500 CHAR) NOT NULL ENABLE, 
	"CC_RECIPIENTS" VARCHAR2(500 CHAR), 
	"STATUS" VARCHAR2(10 CHAR) NOT NULL ENABLE, 
	"SENT_AT" TIMESTAMP (6) NOT NULL ENABLE, 
	"ERROR_MESSAGE" VARCHAR2(500 CHAR), 
	 PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AEP_LEADER"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AEP_LEADER" ;

CREATE UNIQUE INDEX "SYS_C0018947" ON "APMS_NOTIFICATION_LOG" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AEP_LEADER" ;


-- SUPER_LINE_LEADER.APMS_OCR_TASK definition

CREATE TABLE "APMS_OCR_TASK" 
   (	"ID" VARCHAR2(36) NOT NULL ENABLE, 
	"PART_ID" VARCHAR2(36), 
	"FILE_PATH" VARCHAR2(500), 
	"STATUS" VARCHAR2(20) NOT NULL ENABLE, 
	"RESULT_JSON" CLOB, 
	"ERROR_MESSAGE" VARCHAR2(500), 
	"CREATED_BY" VARCHAR2(100) NOT NULL ENABLE, 
	"CREATED_AT" TIMESTAMP (6) NOT NULL ENABLE, 
	"UPDATED_BY" VARCHAR2(100), 
	"UPDATED_AT" TIMESTAMP (6), 
	 CONSTRAINT "PK_APMS_OCR_TASK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AEP_LEADER"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AEP_LEADER" 
 LOB ("RESULT_JSON") STORE AS SECUREFILE (
  TABLESPACE "AEP_LEADER" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

CREATE UNIQUE INDEX "PK_APMS_OCR_TASK" ON "APMS_OCR_TASK" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AEP_LEADER" ;
  CREATE UNIQUE INDEX "SYS_IL0000115013C00005$$" ON "APMS_OCR_TASK" (
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AEP_LEADER" 
  PARALLEL (DEGREE 0 INSTANCES 0) ;
  CREATE INDEX "IDX_OCR_TASK_PART_ID" ON "APMS_OCR_TASK" ("PART_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AEP_LEADER" ;
  CREATE INDEX "IDX_OCR_TASK_STATUS" ON "APMS_OCR_TASK" ("STATUS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AEP_LEADER" ;


-- SUPER_LINE_LEADER.APMS_PART_CODE definition

CREATE TABLE "APMS_PART_CODE" 
   (	"ID" VARCHAR2(36) NOT NULL ENABLE, 
	"PART_CODE" VARCHAR2(100) NOT NULL ENABLE, 
	"BUSINESS_UNIT" VARCHAR2(100), 
	"PRODUCT_PLATFORM" VARCHAR2(100), 
	"CREATED_BY" VARCHAR2(100) NOT NULL ENABLE, 
	"CREATED_AT" TIMESTAMP (6) NOT NULL ENABLE, 
	"UPDATED_BY" VARCHAR2(100), 
	"UPDATED_AT" TIMESTAMP (6), 
	 PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AEP_LEADER"  ENABLE, 
	 UNIQUE ("PART_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AEP_LEADER"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AEP_LEADER" ;

CREATE UNIQUE INDEX "SYS_C0018416" ON "APMS_PART_CODE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AEP_LEADER" ;
  CREATE UNIQUE INDEX "SYS_C0018417" ON "APMS_PART_CODE" ("PART_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AEP_LEADER" ;


-- SUPER_LINE_LEADER.APMS_REPORT_TEMPLATE definition

CREATE TABLE "APMS_REPORT_TEMPLATE" 
   (	"ID" VARCHAR2(36 CHAR), 
	"NAME" VARCHAR2(200 CHAR) NOT NULL ENABLE, 
	"FAILURE_TYPE" VARCHAR2(50 CHAR), 
	"FILE_PATH" VARCHAR2(500 CHAR) NOT NULL ENABLE, 
	"FILE_NAME" VARCHAR2(200 CHAR) NOT NULL ENABLE, 
	"FIELD_DEFINITIONS" VARCHAR2(4000 CHAR), 
	"ENABLED" NUMBER(1,0) DEFAULT 1, 
	"CREATED_BY" VARCHAR2(100 CHAR) NOT NULL ENABLE, 
	"CREATED_AT" TIMESTAMP (6) NOT NULL ENABLE, 
	"UPDATED_BY" VARCHAR2(100 CHAR), 
	"UPDATED_AT" TIMESTAMP (6), 
	"PRODUCT_PLATFORM" VARCHAR2(50 CHAR), 
	 PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AEP_LEADER"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AEP_LEADER" ;

CREATE UNIQUE INDEX "SYS_C0018114" ON "APMS_REPORT_TEMPLATE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AEP_LEADER" ;
  CREATE INDEX "IDX_REPORT_TEMPLATE_FAILURE" ON "APMS_REPORT_TEMPLATE" ("FAILURE_TYPE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AEP_LEADER" ;
  CREATE INDEX "IDX_REPORT_TEMPLATE_PLATFORM" ON "APMS_REPORT_TEMPLATE" ("PRODUCT_PLATFORM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AEP_LEADER" ;


-- SUPER_LINE_LEADER.APMS_SMB_CONFIGURATION definition

CREATE TABLE "APMS_SMB_CONFIGURATION" 
   (	"ID" VARCHAR2(36 CHAR), 
	"HOST" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"SHARE_NAME" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"DOMAIN" VARCHAR2(100 CHAR), 
	"SMB_USER" VARCHAR2(100 CHAR) NOT NULL ENABLE, 
	"SMB_PASSWORD" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"PREFIX" VARCHAR2(100 CHAR) NOT NULL ENABLE, 
	"ENV" VARCHAR2(50 CHAR) NOT NULL ENABLE, 
	"ENABLED" NUMBER(1,0) DEFAULT 1, 
	"CREATED_BY" VARCHAR2(100 CHAR) NOT NULL ENABLE, 
	"CREATED_AT" TIMESTAMP (6) NOT NULL ENABLE, 
	"UPDATED_BY" VARCHAR2(100 CHAR), 
	"UPDATED_AT" TIMESTAMP (6), 
	 PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AEP_LEADER"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AEP_LEADER" ;

CREATE UNIQUE INDEX "SYS_C0019016" ON "APMS_SMB_CONFIGURATION" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AEP_LEADER" ;

COMMENT ON TABLE SUPER_LINE_LEADER.APMS_SMB_CONFIGURATION IS 'SMB存储配置表';
COMMENT ON COLUMN SUPER_LINE_LEADER.APMS_SMB_CONFIGURATION.HOST IS 'SMB服务器地址';
COMMENT ON COLUMN SUPER_LINE_LEADER.APMS_SMB_CONFIGURATION.SHARE_NAME IS '共享名';
COMMENT ON COLUMN SUPER_LINE_LEADER.APMS_SMB_CONFIGURATION."DOMAIN" IS '域';
COMMENT ON COLUMN SUPER_LINE_LEADER.APMS_SMB_CONFIGURATION.SMB_USER IS '登录用户名';
COMMENT ON COLUMN SUPER_LINE_LEADER.APMS_SMB_CONFIGURATION.SMB_PASSWORD IS '登录密码';
COMMENT ON COLUMN SUPER_LINE_LEADER.APMS_SMB_CONFIGURATION.PREFIX IS '路径前缀';
COMMENT ON COLUMN SUPER_LINE_LEADER.APMS_SMB_CONFIGURATION.ENV IS '环境标识';
COMMENT ON COLUMN SUPER_LINE_LEADER.APMS_SMB_CONFIGURATION.ENABLED IS '是否启用';


-- SUPER_LINE_LEADER.APMS_STAT_PARTS definition

CREATE TABLE "APMS_STAT_PARTS" 
   (	"ID" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 ORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"PART_NUMBER" VARCHAR2(30), 
	"PART_CODE" VARCHAR2(50), 
	"ORDER_NUMBER" VARCHAR2(20), 
	"BUSINESS_UNIT" VARCHAR2(50), 
	"PRODUCT_PLATFORM" VARCHAR2(50), 
	"VEHICLE_PRODUCTION_DATE" DATE, 
	"VEHICLE_PURCHASE_DATE" DATE, 
	"VEHICLE_FAILURE_DATE" DATE, 
	"VEHICLE_MILEAGE" NUMBER(10,0), 
	"RESPONSIBLE_ENGINEER" VARCHAR2(100), 
	"ANALYST" VARCHAR2(100), 
	"QC_NO" VARCHAR2(50), 
	"IS_SAMPLE" NUMBER(1,0), 
	"BOSCH_FAILURE_TYPE" VARCHAR2(255), 
	"CUSTOMER_ID" VARCHAR2(36), 
	"CUSTOMER" VARCHAR2(100), 
	"RECEIVE_DATE" DATE, 
	"COMPLAINT_DATE" DATE, 
	"RETURN_QUANTITY" NUMBER(10,0), 
	"CREATED_TIME" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"ANALYST_DURATION" NUMBER(*,0) DEFAULT 0, 
	"COMPLAINT_TYPE" VARCHAR2(20), 
	"PART_PRODUCE_DATE" DATE, 
	"BCSO" VARCHAR2(10), 
	 CONSTRAINT "APMS_STAT_PARTS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AEP_LEADER"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AEP_LEADER" ;

CREATE UNIQUE INDEX "APMS_STAT_PARTS_PK" ON "APMS_STAT_PARTS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AEP_LEADER" ;

COMMENT ON TABLE SUPER_LINE_LEADER.APMS_STAT_PARTS IS '售后件统计报表';
COMMENT ON COLUMN SUPER_LINE_LEADER.APMS_STAT_PARTS.ANALYST_DURATION IS '分析时长 整数';
COMMENT ON COLUMN SUPER_LINE_LEADER.APMS_STAT_PARTS.COMPLAINT_TYPE IS '投诉类型';
COMMENT ON COLUMN SUPER_LINE_LEADER.APMS_STAT_PARTS.PART_PRODUCE_DATE IS '零件生产日期';
COMMENT ON COLUMN SUPER_LINE_LEADER.APMS_STAT_PARTS.BCSO IS '责任判定';


-- SUPER_LINE_LEADER.APMS_IMPORT_LOG_DETAIL definition

CREATE TABLE "APMS_IMPORT_LOG_DETAIL" 
   (	"ID" VARCHAR2(36 CHAR) NOT NULL ENABLE, 
	"IMPORT_ID" VARCHAR2(36 CHAR) NOT NULL ENABLE, 
	"FILE_NAME" VARCHAR2(255 CHAR), 
	"ROW_NUMBER" NUMBER(10,0) NOT NULL ENABLE, 
	"STATUS" VARCHAR2(20 CHAR) NOT NULL ENABLE, 
	"ERROR_CODE" VARCHAR2(50 CHAR), 
	"ERROR_MESSAGE" VARCHAR2(500 CHAR), 
	"RAW_DATA" CLOB, 
	"ORDER_ID" VARCHAR2(36 CHAR), 
	"ORDER_NUMBER" VARCHAR2(50 CHAR), 
	"ORDER_CREATED" CHAR(1 CHAR), 
	"PART_ID" VARCHAR2(36 CHAR), 
	"PART_CODE" VARCHAR2(50 CHAR), 
	"PART_NUMBER" VARCHAR2(50 CHAR), 
	"QC_NO" VARCHAR2(50 CHAR), 
	"CREATED_AT" TIMESTAMP (6) NOT NULL ENABLE, 
	 CONSTRAINT "PK_IMPORT_LOG_DETAIL" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AEP_LEADER"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AEP_LEADER" 
 LOB ("RAW_DATA") STORE AS SECUREFILE (
  TABLESPACE "AEP_LEADER" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

ALTER TABLE "APMS_IMPORT_LOG_DETAIL" ADD CONSTRAINT "FK_IMPORT_LOG_RECORD" FOREIGN KEY ("IMPORT_ID")
	  REFERENCES "APMS_IMPORT_RECORD" ("ID") ON DELETE CASCADE ENABLE;

CREATE UNIQUE INDEX "PK_IMPORT_LOG_DETAIL" ON "APMS_IMPORT_LOG_DETAIL" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AEP_LEADER" ;
  CREATE UNIQUE INDEX "SYS_IL0000115532C00008$$" ON "APMS_IMPORT_LOG_DETAIL" (
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AEP_LEADER" 
  PARALLEL (DEGREE 0 INSTANCES 0) ;
  CREATE INDEX "IDX_IMPORT_LOG_IMPORT_ID" ON "APMS_IMPORT_LOG_DETAIL" ("IMPORT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AEP_LEADER" ;
  CREATE INDEX "IDX_IMPORT_LOG_STATUS" ON "APMS_IMPORT_LOG_DETAIL" ("STATUS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AEP_LEADER" ;
  CREATE INDEX "IDX_IMPORT_LOG_ROW" ON "APMS_IMPORT_LOG_DETAIL" ("IMPORT_ID", "ROW_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AEP_LEADER" ;

COMMENT ON TABLE SUPER_LINE_LEADER.APMS_IMPORT_LOG_DETAIL IS '导入日志明细表，记录每行的导入结果';
COMMENT ON COLUMN SUPER_LINE_LEADER.APMS_IMPORT_LOG_DETAIL.ID IS '主键 UUID';
COMMENT ON COLUMN SUPER_LINE_LEADER.APMS_IMPORT_LOG_DETAIL.IMPORT_ID IS '关联的导入记录ID';
COMMENT ON COLUMN SUPER_LINE_LEADER.APMS_IMPORT_LOG_DETAIL.FILE_NAME IS '文件名（目录导入时有多个文件）';
COMMENT ON COLUMN SUPER_LINE_LEADER.APMS_IMPORT_LOG_DETAIL."ROW_NUMBER" IS '行号';
COMMENT ON COLUMN SUPER_LINE_LEADER.APMS_IMPORT_LOG_DETAIL.STATUS IS '状态：success / failed';
COMMENT ON COLUMN SUPER_LINE_LEADER.APMS_IMPORT_LOG_DETAIL.ERROR_CODE IS '错误代码';
COMMENT ON COLUMN SUPER_LINE_LEADER.APMS_IMPORT_LOG_DETAIL.ERROR_MESSAGE IS '错误信息';
COMMENT ON COLUMN SUPER_LINE_LEADER.APMS_IMPORT_LOG_DETAIL.RAW_DATA IS '原始数据 JSON';
COMMENT ON COLUMN SUPER_LINE_LEADER.APMS_IMPORT_LOG_DETAIL.ORDER_ID IS '退货单ID';
COMMENT ON COLUMN SUPER_LINE_LEADER.APMS_IMPORT_LOG_DETAIL.ORDER_NUMBER IS '退货单号';
COMMENT ON COLUMN SUPER_LINE_LEADER.APMS_IMPORT_LOG_DETAIL.ORDER_CREATED IS '是否为此导入新建退货单：Y/N';
COMMENT ON COLUMN SUPER_LINE_LEADER.APMS_IMPORT_LOG_DETAIL.PART_ID IS '售后件ID';
COMMENT ON COLUMN SUPER_LINE_LEADER.APMS_IMPORT_LOG_DETAIL.PART_CODE IS '博世零件号';
COMMENT ON COLUMN SUPER_LINE_LEADER.APMS_IMPORT_LOG_DETAIL.PART_NUMBER IS '零件编号';
COMMENT ON COLUMN SUPER_LINE_LEADER.APMS_IMPORT_LOG_DETAIL.QC_NO IS 'QC单号';
COMMENT ON COLUMN SUPER_LINE_LEADER.APMS_IMPORT_LOG_DETAIL.CREATED_AT IS '创建时间';


-- SUPER_LINE_LEADER.APMS_RETURN_ORDER definition

CREATE TABLE "APMS_RETURN_ORDER" 
   (	"ID" VARCHAR2(36 CHAR), 
	"ORDER_NUMBER" VARCHAR2(20 CHAR), 
	"CUSTOMER" VARCHAR2(100 CHAR), 
	"RECEIVE_DATE" DATE NOT NULL ENABLE, 
	"COMPLAINT_DATE" DATE NOT NULL ENABLE, 
	"RETURN_METHOD" VARCHAR2(20 CHAR) NOT NULL ENABLE, 
	"TRACKING_NUMBER" VARCHAR2(50 CHAR), 
	"RETURN_QUANTITY" NUMBER(10,0) DEFAULT 0 NOT NULL ENABLE, 
	"STATUS" VARCHAR2(50 CHAR) NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(100 CHAR) NOT NULL ENABLE, 
	"CREATED_AT" TIMESTAMP (6) NOT NULL ENABLE, 
	"UPDATED_BY" VARCHAR2(100 CHAR), 
	"UPDATED_AT" TIMESTAMP (6), 
	"CUSTOMER_ID" VARCHAR2(36 CHAR), 
	"COMPLAINT_TYPE" VARCHAR2(20) NOT NULL ENABLE, 
	"OTHER_INFO" VARCHAR2(500 CHAR), 
	 PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AEP_LEADER"  ENABLE, 
	 UNIQUE ("ORDER_NUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AEP_LEADER"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AEP_LEADER" ;

ALTER TABLE "APMS_RETURN_ORDER" ADD CONSTRAINT "FK_RETURN_ORDER_CUSTOMER" FOREIGN KEY ("CUSTOMER_ID")
	  REFERENCES "APMS_CUSTOMER" ("ID") ENABLE;

CREATE INDEX "IDX_APMS_RO_RECEIVE_DATE" ON "APMS_RETURN_ORDER" ("RECEIVE_DATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AEP_LEADER" ;
  CREATE UNIQUE INDEX "SYS_C0018046" ON "APMS_RETURN_ORDER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AEP_LEADER" ;
  CREATE UNIQUE INDEX "SYS_C0018047" ON "APMS_RETURN_ORDER" ("ORDER_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AEP_LEADER" ;

COMMENT ON COLUMN SUPER_LINE_LEADER.APMS_RETURN_ORDER.COMPLAINT_TYPE IS 'Failure type（失效类型）：BA20代表0km，不能抽样；其他类型可以抽样';


-- SUPER_LINE_LEADER.APMS_ANALYSIS_ORDER definition

CREATE TABLE "APMS_ANALYSIS_ORDER" 
   (	"ID" VARCHAR2(36 CHAR), 
	"ORDER_ID" VARCHAR2(36 CHAR) NOT NULL ENABLE, 
	"ANALYST" VARCHAR2(100 CHAR) NOT NULL ENABLE, 
	"STATUS" VARCHAR2(50 CHAR) NOT NULL ENABLE, 
	"STATUS_CHANGED_AT" TIMESTAMP (6), 
	"CREATED_BY" VARCHAR2(100 CHAR) NOT NULL ENABLE, 
	"CREATED_AT" TIMESTAMP (6) NOT NULL ENABLE, 
	"UPDATED_BY" VARCHAR2(100 CHAR), 
	"UPDATED_AT" TIMESTAMP (6), 
	 PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AEP_LEADER"  ENABLE, 
	 CONSTRAINT "UQ_ANALYSIS_ORDER" UNIQUE ("ORDER_ID", "ANALYST")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AEP_LEADER"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AEP_LEADER" ;

ALTER TABLE "APMS_ANALYSIS_ORDER" ADD FOREIGN KEY ("ORDER_ID")
	  REFERENCES "APMS_RETURN_ORDER" ("ID") ENABLE;

CREATE INDEX "IDX_APMS_AO_STATUS" ON "APMS_ANALYSIS_ORDER" ("STATUS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AEP_LEADER" ;
  CREATE INDEX "IDX_APMS_AO_ANALYST" ON "APMS_ANALYSIS_ORDER" ("ANALYST") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AEP_LEADER" ;
  CREATE UNIQUE INDEX "SYS_C0018278" ON "APMS_ANALYSIS_ORDER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AEP_LEADER" ;
  CREATE UNIQUE INDEX "UQ_ANALYSIS_ORDER" ON "APMS_ANALYSIS_ORDER" ("ORDER_ID", "ANALYST") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AEP_LEADER" ;


-- SUPER_LINE_LEADER.APMS_PART definition

CREATE TABLE "APMS_PART" 
   (	"ID" VARCHAR2(36 CHAR), 
	"PART_NUMBER" VARCHAR2(30 CHAR), 
	"ORDER_ID" VARCHAR2(36 CHAR) NOT NULL ENABLE, 
	"PART_CODE" VARCHAR2(50 CHAR) NOT NULL ENABLE, 
	"BUSINESS_UNIT" VARCHAR2(50 CHAR), 
	"PRODUCT_PLATFORM" VARCHAR2(50 CHAR), 
	"PRODUCTION_SHIFT" VARCHAR2(20 CHAR), 
	"COMPLAINT_TYPE" VARCHAR2(20 CHAR), 
	"VEHICLE_PRODUCTION_DATE" DATE, 
	"VEHICLE_PURCHASE_DATE" DATE, 
	"VEHICLE_FAILURE_DATE" DATE, 
	"VEHICLE_VIN" VARCHAR2(255 CHAR), 
	"VEHICLE_MILEAGE" NUMBER(10,0), 
	"CUSTOMER_DESCRIPTION" VARCHAR2(500 CHAR), 
	"OTHER_DESCRIPTION" VARCHAR2(500 CHAR), 
	"RESPONSIBLE_ENGINEER" VARCHAR2(100 CHAR), 
	"ANALYST" VARCHAR2(100 CHAR), 
	"QC_NO" VARCHAR2(50 CHAR), 
	"IS_SAMPLE" NUMBER(1,0) DEFAULT 0, 
	"STATUS_CHANGED_AT" TIMESTAMP (6), 
	"STATUS" VARCHAR2(50 CHAR) NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(100 CHAR) NOT NULL ENABLE, 
	"CREATED_AT" TIMESTAMP (6) NOT NULL ENABLE, 
	"UPDATED_BY" VARCHAR2(100 CHAR), 
	"UPDATED_AT" TIMESTAMP (6), 
	"CUSTOMER_FAILURE_TYPE" VARCHAR2(50 CHAR), 
	"BOSCH_FAILURE_TYPE" VARCHAR2(255 CHAR), 
	"REPAIR_STATION" VARCHAR2(100 CHAR), 
	"COMPLAINT_LOCATION" VARCHAR2(100 CHAR), 
	"IMAGES" VARCHAR2(2000), 
	"PART_PRODUCTION_DATE" DATE, 
	"OTHER_INFO" VARCHAR2(500 CHAR), 
	 PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AEP_LEADER"  ENABLE, 
	 CONSTRAINT "UK_ORDER_PART_NUMBER" UNIQUE ("ORDER_ID", "PART_NUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AEP_LEADER"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AEP_LEADER" ;

ALTER TABLE "APMS_PART" ADD FOREIGN KEY ("ORDER_ID")
	  REFERENCES "APMS_RETURN_ORDER" ("ID") ENABLE;

CREATE INDEX "IDX_PART_ORDER_ANALYST" ON "APMS_PART" ("ORDER_ID", "ANALYST") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AEP_LEADER" ;
  CREATE INDEX "IDX_APMS_PART_ST_SCAT" ON "APMS_PART" ("STATUS", "STATUS_CHANGED_AT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AEP_LEADER" ;
  CREATE INDEX "IDX_APMS_PART_CREATED_AT" ON "APMS_PART" ("CREATED_AT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AEP_LEADER" ;
  CREATE INDEX "IDX_APMS_PART_TRUNC_CREATED_AT" ON "APMS_PART" (TRUNC("CREATED_AT")) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AEP_LEADER" ;
  CREATE UNIQUE INDEX "UK_ORDER_PART_NUMBER" ON "APMS_PART" ("ORDER_ID", "PART_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AEP_LEADER" ;
  CREATE INDEX "IDX_PART_ORDER_ID" ON "APMS_PART" ("ORDER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AEP_LEADER" ;
  CREATE UNIQUE INDEX "SYS_C0018055" ON "APMS_PART" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AEP_LEADER" ;


-- SUPER_LINE_LEADER.APMS_ANALYSIS_REPORT definition

CREATE TABLE "APMS_ANALYSIS_REPORT" 
   (	"ID" VARCHAR2(36 CHAR), 
	"PART_ID" VARCHAR2(36 CHAR) NOT NULL ENABLE, 
	"TEMPLATE_ID" VARCHAR2(36 CHAR) NOT NULL ENABLE, 
	"CONTENT" VARCHAR2(4000 CHAR), 
	"SUMMARY" VARCHAR2(500 CHAR), 
	"STATUS" VARCHAR2(20 CHAR) NOT NULL ENABLE, 
	"ATTACHMENTS" VARCHAR2(4000), 
	"SUBMITTED_BY" VARCHAR2(100 CHAR), 
	"SUBMITTED_AT" TIMESTAMP (6), 
	"APPROVED_BY" VARCHAR2(100 CHAR), 
	"APPROVED_AT" TIMESTAMP (6), 
	"REJECT_REASON" VARCHAR2(500 CHAR), 
	"CREATED_BY" VARCHAR2(100 CHAR) NOT NULL ENABLE, 
	"CREATED_AT" TIMESTAMP (6) NOT NULL ENABLE, 
	"UPDATED_BY" VARCHAR2(100 CHAR), 
	"UPDATED_AT" TIMESTAMP (6), 
	"RESPONSIBILITY_JUDGMENT" VARCHAR2(50 CHAR), 
	"RESPONSIBILITY" VARCHAR2(1 CHAR), 
	 PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AEP_LEADER"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AEP_LEADER" ;

ALTER TABLE "APMS_ANALYSIS_REPORT" ADD CONSTRAINT "FK_ANALYSIS_REPORT_PART" FOREIGN KEY ("PART_ID")
	  REFERENCES "APMS_PART" ("ID") ENABLE;
  ALTER TABLE "APMS_ANALYSIS_REPORT" ADD CONSTRAINT "FK_ANALYSIS_REPORT_TEMPLATE" FOREIGN KEY ("TEMPLATE_ID")
	  REFERENCES "APMS_REPORT_TEMPLATE" ("ID") ENABLE;

CREATE UNIQUE INDEX "SYS_C0018120" ON "APMS_ANALYSIS_REPORT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AEP_LEADER" ;
  CREATE INDEX "IDX_ANALYSIS_REPORT_PART" ON "APMS_ANALYSIS_REPORT" ("PART_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AEP_LEADER" ;
  CREATE INDEX "IDX_ANALYSIS_REPORT_STATUS" ON "APMS_ANALYSIS_REPORT" ("STATUS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AEP_LEADER" ;
  CREATE INDEX "IDX_ANALYSIS_REPORT_TEMPLATE" ON "APMS_ANALYSIS_REPORT" ("TEMPLATE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AEP_LEADER" ;
  CREATE INDEX "IDX_ANALYSIS_REPORT_RESPONSIBILITY" ON "APMS_ANALYSIS_REPORT" ("RESPONSIBILITY_JUDGMENT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AEP_LEADER" ;
  CREATE INDEX "IDX_ANALYSIS_REPORT_PART_STATUS" ON "APMS_ANALYSIS_REPORT" ("PART_ID", "STATUS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AEP_LEADER" ;
  CREATE INDEX "IDX_ANALYSIS_REPORT_APPROVED_AT" ON "APMS_ANALYSIS_REPORT" ("APPROVED_AT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AEP_LEADER" ;

COMMENT ON COLUMN SUPER_LINE_LEADER.APMS_ANALYSIS_REPORT.RESPONSIBILITY_JUDGMENT IS '责任判定冗余列，避免JSON_VALUE查询性能问题。可选值: BOSCH(我方责任), CUSTOMER(客户责任), SUPPLIER(供应商责任), JOINT(共同责任), UNKNOWN(无法判定)';