-- 添加FAILURE_TYPE字段到退货单表
-- Failure type：失效类型，BA20代表0km，不能抽样，只能走报废流程

-- 添加FAILURE_TYPE字段（如果之前添加过IS_0KM或COMPLAINT_TYPE，先删除）
-- ALTER TABLE APMS_RETURN_ORDER DROP COLUMN IS_0KM;
-- ALTER TABLE APMS_RETURN_ORDER DROP COLUMN COMPLAINT_TYPE;

ALTER TABLE APMS_RETURN_ORDER ADD FAILURE_TYPE VARCHAR2(20 CHAR) NOT NULL;

-- 添加注释
COMMENT ON COLUMN APMS_RETURN_ORDER.FAILURE_TYPE IS 'Failure type（失效类型）：BA20代表0km，不能抽样；其他类型可以抽样';
