-- 导入记录表
-- flyway.enabled=false，此脚本需在 Oracle 中手动执行
-- 执行用户: SUPER_LINE_LEADER

CREATE TABLE APMS_IMPORT_RECORD (
    ID            VARCHAR2(36 CHAR)   NOT NULL,
    IMPORT_TYPE   VARCHAR2(50 CHAR)   NOT NULL,
    FILE_NAME     VARCHAR2(255 CHAR)  NOT NULL,
    STATUS        VARCHAR2(20 CHAR)   NOT NULL,
    TOTAL_COUNT   NUMBER(10)          DEFAULT 0 NOT NULL,
    SUCCESS_COUNT NUMBER(10)          DEFAULT 0 NOT NULL,
    FAIL_COUNT    NUMBER(10)          DEFAULT 0 NOT NULL,
    FAIL_LOGS     CLOB,
    IMPORT_LOGS   CLOB,
    CREATED_BY    VARCHAR2(100 CHAR)  NOT NULL,
    CREATED_AT    TIMESTAMP           NOT NULL,
    CONSTRAINT PK_APMS_IMPORT_RECORD PRIMARY KEY (ID)
);

COMMENT ON TABLE  APMS_IMPORT_RECORD               IS 'Excel 导入历史记录';
COMMENT ON COLUMN APMS_IMPORT_RECORD.ID            IS '主键 UUID';
COMMENT ON COLUMN APMS_IMPORT_RECORD.IMPORT_TYPE   IS '导入类型：return_order / part';
COMMENT ON COLUMN APMS_IMPORT_RECORD.FILE_NAME     IS '上传文件名';
COMMENT ON COLUMN APMS_IMPORT_RECORD.STATUS        IS '状态：processing / completed / failed';
COMMENT ON COLUMN APMS_IMPORT_RECORD.TOTAL_COUNT   IS '数据总行数';
COMMENT ON COLUMN APMS_IMPORT_RECORD.SUCCESS_COUNT IS '成功行数';
COMMENT ON COLUMN APMS_IMPORT_RECORD.FAIL_COUNT    IS '失败行数';
COMMENT ON COLUMN APMS_IMPORT_RECORD.FAIL_LOGS     IS '失败日志 JSON 数组 [{row, error, rawData}]';
COMMENT ON COLUMN APMS_IMPORT_RECORD.IMPORT_LOGS   IS '完整导入日志 JSON 数组（含成功与失败），[{row, status, ...}]';
COMMENT ON COLUMN APMS_IMPORT_RECORD.CREATED_BY    IS '操作人';
COMMENT ON COLUMN APMS_IMPORT_RECORD.CREATED_AT    IS '操作时间';
