-- 创建邮件服务器配置表
CREATE TABLE APMS_EMAIL_CONFIGURATION (
  ID VARCHAR2(36 CHAR) PRIMARY KEY,
  SMTP_HOST VARCHAR2(255 CHAR) NOT NULL,
  SMTP_PORT NUMBER(5) DEFAULT 587,
  EMAIL_FROM VARCHAR2(255 CHAR) NOT NULL,
  EMAIL_PASSWORD VARCHAR2(255 CHAR) NOT NULL,
  ENABLED NUMBER(1) DEFAULT 1,
  CREATED_BY VARCHAR2(100 CHAR) NOT NULL,
  CREATED_AT TIMESTAMP NOT NULL,
  UPDATED_BY VARCHAR2(100 CHAR),
  UPDATED_AT TIMESTAMP
);

-- 添加表注释
COMMENT ON TABLE APMS_EMAIL_CONFIGURATION IS '邮件服务器配置表';
COMMENT ON COLUMN APMS_EMAIL_CONFIGURATION.SMTP_HOST IS 'SMTP服务器地址';
COMMENT ON COLUMN APMS_EMAIL_CONFIGURATION.SMTP_PORT IS 'SMTP服务器端口';
COMMENT ON COLUMN APMS_EMAIL_CONFIGURATION.EMAIL_FROM IS '发件人邮箱';
COMMENT ON COLUMN APMS_EMAIL_CONFIGURATION.EMAIL_PASSWORD IS '邮箱密码';
COMMENT ON COLUMN APMS_EMAIL_CONFIGURATION.ENABLED IS '是否启用';
