-- 添加用户名、域名、显示名称和SSL配置字段
ALTER TABLE APMS_EMAIL_CONFIGURATION ADD SMTP_USERNAME VARCHAR2(255 CHAR);
ALTER TABLE APMS_EMAIL_CONFIGURATION ADD SMTP_DOMAIN VARCHAR2(255 CHAR);
ALTER TABLE APMS_EMAIL_CONFIGURATION ADD EMAIL_FROM_DISPLAY_NAME VARCHAR2(255 CHAR);
ALTER TABLE APMS_EMAIL_CONFIGURATION ADD ENABLE_SSL NUMBER(1) DEFAULT 0;

-- 更新端口默认值为25
COMMENT ON COLUMN APMS_EMAIL_CONFIGURATION.SMTP_PORT IS 'SMTP服务器端口 (25-标准SMTP, 587-STARTTLS)';

-- 添加新字段注释
COMMENT ON COLUMN APMS_EMAIL_CONFIGURATION.SMTP_USERNAME IS 'SMTP认证用户名';
COMMENT ON COLUMN APMS_EMAIL_CONFIGURATION.SMTP_DOMAIN IS 'SMTP认证域';
COMMENT ON COLUMN APMS_EMAIL_CONFIGURATION.EMAIL_FROM_DISPLAY_NAME IS '发件人显示名称';
COMMENT ON COLUMN APMS_EMAIL_CONFIGURATION.ENABLE_SSL IS '是否启用SSL加密';
