CREATE TABLE APMS_ANALYSIS_ORDER (
  ID                VARCHAR2(36 CHAR)  PRIMARY KEY,
  ORDER_ID          VARCHAR2(36 CHAR)  NOT NULL REFERENCES APMS_RETURN_ORDER(ID),
  ANALYST           VARCHAR2(100 CHAR) NOT NULL,
  STATUS            VARCHAR2(50 CHAR)  NOT NULL,
  STATUS_CHANGED_AT TIMESTAMP,
  CREATED_BY        VARCHAR2(100 CHAR) NOT NULL,
  CREATED_AT        TIMESTAMP          NOT NULL,
  UPDATED_BY        VARCHAR2(100 CHAR),
  UPDATED_AT        TIMESTAMP,
  CONSTRAINT UQ_ANALYSIS_ORDER UNIQUE (ORDER_ID, ANALYST)
);
