CREATE TABLE APMS_PART_CODE (
    ID VARCHAR(36) NOT NULL,
    PART_CODE VARCHAR(100) NOT NULL UNIQUE,
    BUSINESS_UNIT VARCHAR(100),
    PRODUCT_PLATFORM VARCHAR(100),
    CREATED_BY VARCHAR(100) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_BY VARCHAR(100),
    UPDATED_AT TIMESTAMP,
    PRIMARY KEY (ID)
);
