-- V24: Remove PRODUCT_CATEGORY from APMS_PART and rename back to PRODUCT_PLATFORM in APMS_REPORT_TEMPLATE
-- Date: 2026-04-01
-- Description: Revert V15 changes for APMS_REPORT_TEMPLATE and remove PRODUCT_CATEGORY from APMS_PART
-- Requirements:
--   - APMS_PART: Drop PRODUCT_CATEGORY column (it was added in V13)
--   - APMS_REPORT_TEMPLATE: Rename PRODUCT_CATEGORY back to PRODUCT_PLATFORM (reverting V15)
--   - Template matching now uses productPlatform + failureType instead of productCategory + failureType
--   - Part entity will no longer have a product category field

-- Step 1: Drop PRODUCT_CATEGORY column from APMS_PART
ALTER TABLE APMS_PART DROP COLUMN PRODUCT_CATEGORY;

-- Step 2: Add PRODUCT_PLATFORM column to APMS_REPORT_TEMPLATE
ALTER TABLE APMS_REPORT_TEMPLATE ADD PRODUCT_PLATFORM VARCHAR2(50 CHAR);

-- Step 3: Copy data from PRODUCT_CATEGORY to PRODUCT_PLATFORM
UPDATE APMS_REPORT_TEMPLATE SET PRODUCT_PLATFORM = PRODUCT_CATEGORY WHERE PRODUCT_CATEGORY IS NOT NULL;

-- Step 4: Drop old index on PRODUCT_CATEGORY
DROP INDEX IDX_REPORT_TEMPLATE_CATEGORY;

-- Step 5: Drop old column PRODUCT_CATEGORY
ALTER TABLE APMS_REPORT_TEMPLATE DROP COLUMN PRODUCT_CATEGORY;

-- Step 6: Create new index on PRODUCT_PLATFORM
CREATE INDEX IDX_REPORT_TEMPLATE_PLATFORM ON APMS_REPORT_TEMPLATE(PRODUCT_PLATFORM);

-- Note: IDX_REPORT_TEMPLATE_FAILURE index remains unchanged as FAILURE_TYPE is still used
