CREATE TABLE APMS_OCR_TASK (
    ID              VARCHAR2(36)    NOT NULL,
    PART_ID         VARCHAR2(36),
    FILE_PATH       VARCHAR2(500),
    STATUS          VARCHAR2(20)    NOT NULL,
    RESULT_JSON     CLOB,
    ERROR_MESSAGE   VARCHAR2(500),
    CREATED_BY      VARCHAR2(100)   NOT NULL,
    CREATED_AT      TIMESTAMP       NOT NULL,
    UPDATED_BY      VARCHAR2(100),
    UPDATED_AT      TIMESTAMP,
    CONSTRAINT PK_APMS_OCR_TASK PRIMARY KEY (ID)
);

CREATE INDEX IDX_OCR_TASK_PART_ID ON APMS_OCR_TASK (PART_ID);
CREATE INDEX IDX_OCR_TASK_STATUS  ON APMS_OCR_TASK (STATUS);
