-- Dashboard performance indexes
-- Targets: stats / tasks / trend endpoints

-- APMS_PART: warning/overdue queries
CREATE INDEX IDX_APMS_PART_ST_SCAT ON APMS_PART (STATUS, STATUS_CHANGED_AT);

-- APMS_RETURN_ORDER: trend by receive date
CREATE INDEX IDX_APMS_RO_RECEIVE_DATE ON APMS_RETURN_ORDER (RECEIVE_DATE);

-- APMS_PART: trend by created time
CREATE INDEX IDX_APMS_PART_CREATED_AT ON APMS_PART (CREATED_AT);

-- APMS_ANALYSIS_REPORT: pending approval tasks
CREATE INDEX IDX_APMS_AR_STATUS ON APMS_ANALYSIS_REPORT (STATUS);

-- APMS_ANALYSIS_ORDER: scrap confirm tasks
CREATE INDEX IDX_APMS_AO_STATUS ON APMS_ANALYSIS_ORDER (STATUS);
