-- Dashboard trend optimization
-- Create function-based index to speed up GROUP BY TRUNC(CREATED_AT) on APMS_PART

DECLARE
	idx_count NUMBER;
BEGIN
	SELECT COUNT(*) INTO idx_count
	FROM USER_INDEXES
	WHERE INDEX_NAME = 'IDX_APMS_PART_TRUNC_CREATED_AT';

	IF idx_count = 0 THEN
		EXECUTE IMMEDIATE 'CREATE INDEX IDX_APMS_PART_TRUNC_CREATED_AT ON APMS_PART (TRUNC(CREATED_AT))';
	END IF;
END;
/
