CREATE TABLE APMS_AFTERMARKET_PART (
                                  ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  PART_CODE VARCHAR2(50) NOT NULL,
                                  NAME VARCHAR2(100),
                                  SUPPLIER_ID NUMBER,
                                  CONSTRAINT FK_PART_SUPPLIER FOREIGN KEY (SUPPLIER_ID) REFERENCES APMS_SUPPLIER(ID)
);
