-- 导入日志明细表
-- 用于存储导入过程中的详细日志，替代 CLOB 字段中的 JSON 数据
-- 性能优化：避免频繁更新 CLOB 字段
-- flyway.enabled=false，此脚本需在 Oracle 中手动执行
-- 执行用户: SUPER_LINE_LEADER

CREATE TABLE APMS_IMPORT_LOG_DETAIL (
    ID              VARCHAR2(36 CHAR)   NOT NULL,
    IMPORT_ID       VARCHAR2(36 CHAR)   NOT NULL,
    FILE_NAME       VARCHAR2(255 CHAR),
    ROW_NUMBER      NUMBER(10)          NOT NULL,
    STATUS          VARCHAR2(20 CHAR)   NOT NULL,
    ERROR_CODE      VARCHAR2(50 CHAR),
    ERROR_MESSAGE   VARCHAR2(500 CHAR),
    RAW_DATA        CLOB,
    ORDER_ID        VARCHAR2(36 CHAR),
    ORDER_NUMBER    VARCHAR2(50 CHAR),
    ORDER_CREATED   CHAR(1 CHAR),
    PART_ID         VARCHAR2(36 CHAR),
    PART_CODE       VARCHAR2(50 CHAR),
    PART_NUMBER     VARCHAR2(50 CHAR),
    QC_NO           VARCHAR2(50 CHAR),
    CREATED_AT      TIMESTAMP           NOT NULL,
    CONSTRAINT PK_IMPORT_LOG_DETAIL PRIMARY KEY (ID),
    CONSTRAINT FK_IMPORT_LOG_RECORD FOREIGN KEY (IMPORT_ID)
        REFERENCES APMS_IMPORT_RECORD(ID) ON DELETE CASCADE
);

-- 创建索引以提高查询性能
CREATE INDEX IDX_IMPORT_LOG_IMPORT_ID ON APMS_IMPORT_LOG_DETAIL(IMPORT_ID);
CREATE INDEX IDX_IMPORT_LOG_STATUS ON APMS_IMPORT_LOG_DETAIL(STATUS);
CREATE INDEX IDX_IMPORT_LOG_ROW ON APMS_IMPORT_LOG_DETAIL(IMPORT_ID, ROW_NUMBER);

-- 添加表和字段注释
COMMENT ON TABLE  APMS_IMPORT_LOG_DETAIL            IS '导入日志明细表，记录每行的导入结果';
COMMENT ON COLUMN APMS_IMPORT_LOG_DETAIL.ID         IS '主键 UUID';
COMMENT ON COLUMN APMS_IMPORT_LOG_DETAIL.IMPORT_ID  IS '关联的导入记录ID';
COMMENT ON COLUMN APMS_IMPORT_LOG_DETAIL.FILE_NAME  IS '文件名（目录导入时有多个文件）';
COMMENT ON COLUMN APMS_IMPORT_LOG_DETAIL.ROW_NUMBER IS '行号';
COMMENT ON COLUMN APMS_IMPORT_LOG_DETAIL.STATUS     IS '状态：success / failed';
COMMENT ON COLUMN APMS_IMPORT_LOG_DETAIL.ERROR_CODE IS '错误代码';
COMMENT ON COLUMN APMS_IMPORT_LOG_DETAIL.ERROR_MESSAGE IS '错误信息';
COMMENT ON COLUMN APMS_IMPORT_LOG_DETAIL.RAW_DATA   IS '原始数据 JSON';
COMMENT ON COLUMN APMS_IMPORT_LOG_DETAIL.ORDER_ID   IS '退货单ID';
COMMENT ON COLUMN APMS_IMPORT_LOG_DETAIL.ORDER_NUMBER IS '退货单号';
COMMENT ON COLUMN APMS_IMPORT_LOG_DETAIL.ORDER_CREATED IS '是否为此导入新建退货单：Y/N';
COMMENT ON COLUMN APMS_IMPORT_LOG_DETAIL.PART_ID    IS '售后件ID';
COMMENT ON COLUMN APMS_IMPORT_LOG_DETAIL.PART_CODE  IS '博世零件号';
COMMENT ON COLUMN APMS_IMPORT_LOG_DETAIL.PART_NUMBER IS '零件编号';
COMMENT ON COLUMN APMS_IMPORT_LOG_DETAIL.QC_NO      IS 'QC单号';
COMMENT ON COLUMN APMS_IMPORT_LOG_DETAIL.CREATED_AT IS '创建时间';
