INSERT INTO APMS_SUPPLIER (NAME) VALUES ('Bosch');
INSERT INTO APMS_SUPPLIER (NAME) VALUES ('Denso');

INSERT INTO APMS_AFTERMARKET_PART (PART_CODE, NAME, SUPPLIER_ID) VALUES ('P001', 'Brake Pad', 1);
INSERT INTO APMS_AFTERMARKET_PART (PART_CODE, NAME, SUPPLIER_ID) VALUES ('P002', 'Oil Filter', 2);
INSERT INTO APMS_AFTERMARKET_PART (PART_CODE, NAME, SUPPLIER_ID) VALUES ('P003', 'Air Filter', 2);
