INSERT INTO APMS_SUPPLIER (NAME)
  SELECT 'Bosch' FROM DUAL
  WHERE NOT EXISTS (SELECT 1 FROM APMS_SUPPLIER WHERE NAME = 'Bosch');

INSERT INTO APMS_SUPPLIER (NAME)
  SELECT 'Denso' FROM DUAL
  WHERE NOT EXISTS (SELECT 1 FROM APMS_SUPPLIER WHERE NAME = 'Denso');

INSERT INTO APMS_AFTERMARKET_PART (PART_CODE, NAME, SUPPLIER_ID)
  SELECT 'P001', 'Brake Pad', 1 FROM DUAL
  WHERE NOT EXISTS (SELECT 1 FROM APMS_AFTERMARKET_PART WHERE PART_CODE = 'P001');

INSERT INTO APMS_AFTERMARKET_PART (PART_CODE, NAME, SUPPLIER_ID)
  SELECT 'P002', 'Oil Filter', 2 FROM DUAL
  WHERE NOT EXISTS (SELECT 1 FROM APMS_AFTERMARKET_PART WHERE PART_CODE = 'P002');

INSERT INTO APMS_AFTERMARKET_PART (PART_CODE, NAME, SUPPLIER_ID)
  SELECT 'P003', 'Air Filter', 2 FROM DUAL
  WHERE NOT EXISTS (SELECT 1 FROM APMS_AFTERMARKET_PART WHERE PART_CODE = 'P003');
