CREATE TABLE APMS_NOTIFICATION_LOG (
    ID                VARCHAR2(36) NOT NULL,
    PART_ID           VARCHAR2(36) NOT NULL,
    NOTIFICATION_TYPE VARCHAR2(30) NOT NULL,
    RECIPIENTS        VARCHAR2(500) NOT NULL,
    CC_RECIPIENTS     VARCHAR2(500),
    STATUS            VARCHAR2(10) NOT NULL,
    SENT_AT           TIMESTAMP NOT NULL,
    ERROR_MESSAGE     VARCHAR2(500),
    CONSTRAINT PK_NOTIFICATION_LOG PRIMARY KEY (ID)
);

CREATE INDEX IDX_NOTIFICATION_PART_TYPE ON APMS_NOTIFICATION_LOG (PART_ID, NOTIFICATION_TYPE);

COMMENT ON TABLE APMS_NOTIFICATION_LOG IS '邮件通知发送记录';
COMMENT ON COLUMN APMS_NOTIFICATION_LOG.NOTIFICATION_TYPE IS '通知类型: WARNING/OVERDUE/APPROVAL_REMINDER/RESPONSIBILITY/ZERO_KM';
COMMENT ON COLUMN APMS_NOTIFICATION_LOG.STATUS IS '发送状态: SUCCESS/FAILED';
