-- 创建SMB存储配置表
CREATE TABLE APMS_SMB_CONFIGURATION (
  ID           VARCHAR2(36 CHAR)  PRIMARY KEY,
  HOST         VARCHAR2(255 CHAR) NOT NULL,
  SHARE_NAME   VARCHAR2(255 CHAR) NOT NULL,
  DOMAIN       VARCHAR2(100 CHAR),
  SMB_USER     VARCHAR2(100 CHAR) NOT NULL,
  SMB_PASSWORD VARCHAR2(255 CHAR) NOT NULL,
  PREFIX       VARCHAR2(100 CHAR) NOT NULL,
  ENV          VARCHAR2(50 CHAR)  NOT NULL,
  ENABLED      NUMBER(1)          DEFAULT 1,
  CREATED_BY   VARCHAR2(100 CHAR) NOT NULL,
  CREATED_AT   TIMESTAMP          NOT NULL,
  UPDATED_BY   VARCHAR2(100 CHAR),
  UPDATED_AT   TIMESTAMP
);

COMMENT ON TABLE APMS_SMB_CONFIGURATION IS 'SMB存储配置表';
COMMENT ON COLUMN APMS_SMB_CONFIGURATION.HOST IS 'SMB服务器地址';
COMMENT ON COLUMN APMS_SMB_CONFIGURATION.SHARE_NAME IS '共享名';
COMMENT ON COLUMN APMS_SMB_CONFIGURATION.DOMAIN IS '域';
COMMENT ON COLUMN APMS_SMB_CONFIGURATION.SMB_USER IS '登录用户名';
COMMENT ON COLUMN APMS_SMB_CONFIGURATION.SMB_PASSWORD IS '登录密码';
COMMENT ON COLUMN APMS_SMB_CONFIGURATION.PREFIX IS '路径前缀';
COMMENT ON COLUMN APMS_SMB_CONFIGURATION.ENV IS '环境标识';
COMMENT ON COLUMN APMS_SMB_CONFIGURATION.ENABLED IS '是否启用';
