-- Drop unused RESPONSIBILITY_JUDGMENT column and its index
-- The actual responsibility field uses the RESPONSIBILITY column (VARCHAR2(1))

DROP INDEX IDX_ANALYSIS_REPORT_RESPONSIBILITY;
ALTER TABLE APMS_ANALYSIS_REPORT DROP COLUMN RESPONSIBILITY_JUDGMENT;
