CREATE TABLE APMS_RETURN_ORDER (
  ID               VARCHAR2(36 CHAR)  PRIMARY KEY,
  ORDER_NUMBER     VARCHAR2(20 CHAR)  UNIQUE,
  CUSTOMER         VARCHAR2(100 CHAR) NOT NULL,
  RECEIVE_DATE     DATE               NOT NULL,
  COMPLAINT_DATE   DATE               NOT NULL,
  RETURN_METHOD    VARCHAR2(20 CHAR)  NOT NULL,
  TRACKING_NUMBER  VARCHAR2(50 CHAR),
  RETURN_QUANTITY  NUMBER(10)         DEFAULT 0 NOT NULL,
  DESCRIPTION      VARCHAR2(500 CHAR),
  STATUS           VARCHAR2(50 CHAR)  NOT NULL,
  CREATED_BY       VARCHAR2(100 CHAR) NOT NULL,
  CREATED_AT       TIMESTAMP          NOT NULL,
  UPDATED_BY       VARCHAR2(100 CHAR),
  UPDATED_AT       TIMESTAMP
);
