-- V53: 为 APMS_NOTIFICATION_LOG 新增 ANALYSIS_ORDER_ID，并放宽 PART_ID 为可空
-- 审批超期提醒(APPROVAL_REMINDER)按分析批次维度记录与去重，该类记录无 part，PART_ID 为 NULL。
-- 全部用 EXECUTE IMMEDIATE 包在 PL/SQL 块里，避免依赖 SQL 客户端对裸 ALTER 的执行顺序。

DECLARE
  v_col NUMBER;
  v_nullable VARCHAR2(1);
BEGIN
  -- 1) 新增 ANALYSIS_ORDER_ID 列（幂等）
  SELECT COUNT(*) INTO v_col
  FROM user_tab_columns
  WHERE table_name = 'APMS_NOTIFICATION_LOG'
    AND column_name = 'ANALYSIS_ORDER_ID';
  IF v_col = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE APMS_NOTIFICATION_LOG ADD ANALYSIS_ORDER_ID VARCHAR2(36)';
    DBMS_OUTPUT.PUT_LINE('已添加 ANALYSIS_ORDER_ID 列');
  ELSE
    DBMS_OUTPUT.PUT_LINE('ANALYSIS_ORDER_ID 列已存在，跳过');
  END IF;

  -- 2) PART_ID 放宽为可空（幂等：仅在当前为 NOT NULL 时执行）
  SELECT NULLABLE INTO v_nullable
  FROM user_tab_columns
  WHERE table_name = 'APMS_NOTIFICATION_LOG'
    AND column_name = 'PART_ID';
  IF v_nullable = 'N' THEN
    EXECUTE IMMEDIATE 'ALTER TABLE APMS_NOTIFICATION_LOG MODIFY PART_ID NULL';
    DBMS_OUTPUT.PUT_LINE('已将 PART_ID 放宽为可空');
  ELSE
    DBMS_OUTPUT.PUT_LINE('PART_ID 已为可空，跳过');
  END IF;

  EXECUTE IMMEDIATE 'COMMENT ON COLUMN APMS_NOTIFICATION_LOG.ANALYSIS_ORDER_ID IS ''关联分析批次ID，仅 APPROVAL_REMINDER 使用；其他类型为 NULL''';
  EXECUTE IMMEDIATE 'COMMENT ON COLUMN APMS_NOTIFICATION_LOG.PART_ID IS ''关联售后件ID，APPROVAL_REMINDER 时为 NULL''';
END;
/
