-- 创建客户表
CREATE TABLE APMS_CUSTOMER (
  ID VARCHAR2(36 CHAR) PRIMARY KEY,
  NAME VARCHAR2(100 CHAR) NOT NULL UNIQUE,
  CODE VARCHAR2(50 CHAR) NOT NULL UNIQUE,
  CREATED_BY VARCHAR2(100 CHAR) NOT NULL,
  CREATED_AT TIMESTAMP NOT NULL,
  UPDATED_BY VARCHAR2(100 CHAR),
  UPDATED_AT TIMESTAMP
);

-- 插入初始客户数据
INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), '一汽大众', 'FAW-VW', 'SYSTEM', SYSTIMESTAMP FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = 'FAW-VW');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), '上汽大众', 'SAIC-VW', 'SYSTEM', SYSTIMESTAMP FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = 'SAIC-VW');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), '东风日产', 'DONGFENG-NISSAN', 'SYSTEM', SYSTIMESTAMP FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = 'DONGFENG-NISSAN');

INSERT INTO APMS_CUSTOMER (ID, NAME, CODE, CREATED_BY, CREATED_AT)
SELECT SYS_GUID(), '北京奔驰', 'BBAC', 'SYSTEM', SYSTIMESTAMP FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM APMS_CUSTOMER WHERE CODE = 'BBAC');
