CREATE TABLE APMS_REPORT_TEMPLATE (
  ID VARCHAR2(36 CHAR) PRIMARY KEY,
  NAME VARCHAR2(200 CHAR) NOT NULL,
  PRODUCT_PLATFORM VARCHAR2(50 CHAR),
  FAILURE_TYPE VARCHAR2(50 CHAR),
  FILE_PATH VARCHAR2(500 CHAR) NOT NULL,
  FILE_NAME VARCHAR2(200 CHAR) NOT NULL,
  FIELD_DEFINITIONS VARCHAR2(4000 CHAR),
  ENABLED NUMBER(1) DEFAULT 1,
  CREATED_BY VARCHAR2(100 CHAR) NOT NULL,
  CREATED_AT TIMESTAMP NOT NULL,
  UPDATED_BY VARCHAR2(100 CHAR),
  UPDATED_AT TIMESTAMP
);

CREATE INDEX IDX_REPORT_TEMPLATE_PLATFORM ON APMS_REPORT_TEMPLATE(PRODUCT_PLATFORM);
CREATE INDEX IDX_REPORT_TEMPLATE_FAILURE ON APMS_REPORT_TEMPLATE(FAILURE_TYPE);
