CREATE TABLE APMS_ANALYSIS_REPORT (
  ID VARCHAR2(36 CHAR) PRIMARY KEY,
  PART_ID VARCHAR2(36 CHAR) NOT NULL,
  TEMPLATE_ID VARCHAR2(36 CHAR) NOT NULL,
  CONTENT VARCHAR2(4000 CHAR),
  SUMMARY VARCHAR2(500 CHAR),
  STATUS VARCHAR2(20 CHAR) NOT NULL,
  ATTACHMENTS VARCHAR2(1000 CHAR),
  SUBMITTED_BY VARCHAR2(100 CHAR),
  SUBMITTED_AT TIMESTAMP,
  APPROVED_BY VARCHAR2(100 CHAR),
  APPROVED_AT TIMESTAMP,
  REJECT_REASON VARCHAR2(500 CHAR),
  CREATED_BY VARCHAR2(100 CHAR) NOT NULL,
  CREATED_AT TIMESTAMP NOT NULL,
  UPDATED_BY VARCHAR2(100 CHAR),
  UPDATED_AT TIMESTAMP,
  CONSTRAINT FK_ANALYSIS_REPORT_PART FOREIGN KEY (PART_ID) REFERENCES APMS_PART(ID),
  CONSTRAINT FK_ANALYSIS_REPORT_TEMPLATE FOREIGN KEY (TEMPLATE_ID) REFERENCES APMS_REPORT_TEMPLATE(ID)
);

CREATE INDEX IDX_ANALYSIS_REPORT_PART ON APMS_ANALYSIS_REPORT(PART_ID);
CREATE INDEX IDX_ANALYSIS_REPORT_STATUS ON APMS_ANALYSIS_REPORT(STATUS);
CREATE INDEX IDX_ANALYSIS_REPORT_TEMPLATE ON APMS_ANALYSIS_REPORT(TEMPLATE_ID);
